- include_vars: "{{ ansible_os_family }}.yml"

- name: install package with apt-get
  yum: name="{{ item }}" state=latest
  with_items: 
    - "{{ common_package }}"
    - "{{ package }}"

- name: clone pyenv
  git: repo={{ pyenv_repo }} dest={{ pyenv_path }}

- name: install virtualenv as pyenv plugin
  git: repo={{ virtualenv_repo }} dest={{ virtualenv_path }}

- name: add pyenv path
  shell: > 
    echo 'export PYENV_ROOT="{{ pyenv_path }}"' >> /etc/profile.d/pyenv.sh;
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> /etc/profile.d/pyenv.sh;

- name: activate code for pyenv
  shell: echo 'eval "$(pyenv init -)"' >> /etc/profile.d/pyenv.sh

- name: activate code for virtualenv
  shell: echo 'eval "$(pyenv virtualenv-init -)"' >> /etc/profile.d/pyenv.sh

- name: initialize pyenv
  shell: bash -lc "source /etc/profile.d/pyenv.sh"