- name: clone pyenv
  git: repo={{ pyenv_repo }} dest={{ pyenv_path }}

- name: install virtualenv as pyenv plugin
  git: repo={{ virtualenv_repo }} dest={{ virtualenv_path }}

- name: add pyenv path
  shell: > 
    echo 'export PYENV_ROOT="{{ pyenv_home }}"' >> ~/.bash_profile;
    echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile;

- name: activate code for pyenv
  shell: echo 'eval "$(pyenv init -)"' >> ~/.bash_profile

- name: activate code for virtualenv
  shell: echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bash_profile

- name: initialize pyenv
  shell: bash -lc "source ~/.bash_profile"