selected_scheme scheme-small
TEXDIR /usr/local/texlive/2017
TEXMFCONFIG /usr/local/.texlive2017/texmf-config
TEXMFHOME /usr/local/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2017/texmf-config
TEXMFSYSVAR /usr/local/texlive/2017/texmf-var
TEXMFVAR /usr/local/.texlive2017/texmf-var
binary_x86_64-linux 1
option_doc 0
option_src 0