- name: mkdir for gitbucket.war
  shell: mkdir -p {{ war_dir }}

- name: mkdir for app home
  shell: mkdir -p {{ apphome }}

- name: mkdir for logfile
  shell: mkdir -p {{ logdir }}

- name: download war file
  get_url: url={{ url_war }} sha256sum={{ csum }} dest={{ war_dir }}/gitbucket-{{ version }}.war force=True

- name: create sym link
  shell: ln -sf {{ war_dir }}/gitbucket-{{ version }}.war {{ apphome }}/gitbucket.war

- name: create startup shell
  template: src=startup.sh.j2 dest={{ apphome }}/startup.sh mode=0755